some linking problem solved

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9660,10 +9660,9 @@ _ACEOF
         LIBS="-llapack -lblas $LIBS"
       fi
     else
-#      { { echo "$as_me:$LINENO: error: \"Cannot find liblapack!\"" >&5
-#echo "$as_me: error: \"Cannot find liblapack!\"" >&2;}
-#   { (exit 1); exit 1; }; }
-        LIBS="-llapack -lblas $LIBS"
+      { { echo "$as_me:$LINENO: error: \"Cannot find liblapack!\"" >&5
+echo "$as_me: error: \"Cannot find liblapack!\"" >&2;}
+   { (exit 1); exit 1; }; }
     fi
     LIBS="$LIBS $F2C"
   fi
@@ -10021,7 +10020,7 @@ if test ! -e test; then
 fi
 
 
-LIBS="-lhmc -lsolver -llinalg $LIBS"
+LIBS="-lhmc -lsolver -llinalg -lhmc $LIBS"
 AUTOCONF=autoconf
 
 #AC_CONFIG_SUBDIRS(lime)
